### ISSUE TITLE
USB gadget mode enabled in the image to allow single wire connection to machine. 

### ISSUE THREAD

**Issue by EnDeRWiGiN** [ModBros/mobro-raspberrypi#1]
Hey, so I found the Pull associated with USB gadget mode.

https://github.com/raspberrypi/linux/pull/1239

Could this be added to the image?

Also looking around the USB gadget mode is supported by Raspberry Pi Zero, Zero W, Model A, Model A+, and PI 4. This would allow you to only have one connection to the Pi and the Pi would have its own private network. 

Setting this up manually would be very difficult but if it could be included in the configurator or at least have the option to edit the config file that would make this process way easier!

See forum for the hard way: [Using RNDIS/Ethernet to connect Raspberry Pi Zero to a computer network.](https://www.mod-bros.com/en/forum/t/using-rndis-ethernet-to-connect-raspberry-pi-zero-to-computer-network~926)

**Comment by digaus** [comment]
Any progress on this? Planning to use it with a Pi Zero connected to onboard USB 2.0 header.

**Comment by EnDeRWiGiN** [comment]
I was able to get it working using @stanoba fork. You can use that and follow the instruction on the [pull request](https://github.com/ModBros/mobro-raspberrypi/pull/6) or you can try to get the mod bros app to run on the normal raspberry pi OS. Those instructions are on the forums: 

[How to use Mobro app on normal Raspberry PI OS in desktop mode (without mobro custom OS image](https://www.mod-bros.com/en/forum/t/guide-how-to-use-mobro-app-on-normal-raspberry-pi-os-in-desktop-mode-without-mobro-custom-os-image~1267)
OR
[Ethernet to connect Raspberry Pi Zero](https://www.mod-bros.com/en/forum/t/using-rndis-ethernet-to-connect-raspberry-pi-zero-to-computer-network~926)

**Comment by digaus** [comment]
> I was able to get it working using @stanoba fork. You can use that and follow the instruction on the [pull request](https://github.com/ModBros/mobro-raspberrypi/pull/6) or you can try to get the mod bros app to run on the normal raspberry pi OS. Those instructions are on the forums:
> 
> [How to use Mobro app on normal Raspberry PI OS in desktop mode (without mobro custom OS image](https://www.mod-bros.com/en/forum/t/guide-how-to-use-mobro-app-on-normal-raspberry-pi-os-in-desktop-mode-without-mobro-custom-os-image~1267)
> OR
> [Ethernet to connect Raspberry Pi Zero](https://www.mod-bros.com/en/forum/t/using-rndis-ethernet-to-connect-raspberry-pi-zero-to-computer-network~926)

Cool thanks. Official support would be nice though :) not that familiar with RPI but I have to decide if I go Zero or Zero W

**Comment by EnDeRWiGiN** [comment]
> Cool thanks. Official support would be nice though :) not that familiar with RPI but I have to decide if I go Zero or Zero W

I would just get the Zero W. It is double the price, but it is more versatile and is easier to diagnose problems. Also, it has more supported boards. The Zero /W does not have much performance, so the screen's refresh rate will be low. With no overclock, I was getting 15 fps. With an overclock, I was in the 20+ fps range. Suppose you will do this more than once and have the system down, then the Zero will work. Also, finding stock for the Zero is harder.

If you care about performance and want it to be silky smooth, the Raspberry Pi Model A, Model A+, and PI 4 support a single wire connection. The PI4 is the easiest to implement, but they all are a little hard to implement than just the Zero /W. Also, the PI4 is great for other projects if you want to repurpose it.

**Comment by digaus** [comment]
Decided to go with the Pi 4. Works nicely :) now only waiting for official USB only version.


![20210122_222909](https://user-images.githubusercontent.com/15358538/105550428-ad5f8180-5d01-11eb-99a1-e86e5fc29b9c.jpg)
