### ISSUE TITLE
Can't seem to get screen rotation to work (v12)

### ISSUE THREAD

**Issue by GeorgeWells** [ModBros/mobro-raspberrypi#7]
I've grabbed v12 and applied the same setup as before (180 rotation) and everything works besides the screen appearing upside down. I've tried going between no rotation and 180 rotation, neither seem to make a difference.

Model: Pi 3B+
Display driver: GoodTFT - MHS35-show

**Comment by Seraksab** [comment]
I don't have a screen for that specific driver, but I could reproduce this with the 'LCD35-show' driver as well
The rotation is not applied as it seems

Thanks for reporting

**Comment by Seraksab** [comment]
I already identified and hopefully fixed the issue
At least the rotation on the 'LCD35-show' driver on my end is working now again

Could you try [this version here](https://drive.google.com/u/0/uc?id=1Ub9THOEFp6Ry5dY3cBVDSGFQ5baEMp65&export=download) and check if it also fixes the issue with your driver?

**Comment by GeorgeWells** [comment]
Looks perfect! Thank you :)

**Comment by Seraksab** [comment]
fix has been included in v12.1
